<?php

namespace fm\mainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * contactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactoRepository extends EntityRepository
{
}
