parameters:
#    erp.example.class: fm\erpBundle\Example

services:
#    erp.example:
#        class: %erp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
                - { name: twig.extension }