_kit_route:
    resource: "@KitBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /{_locale}
    schemes:  [%httpProtocol%]
    requirements:
        _locale: en|es|fr|it|de|pt