version: '2'

services:

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  composer_install:
    image: composer
    restart: 'no'
    command: install
    volumes:
      - .:/app
    depends_on:
      - php

  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    links:
      - php
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443

  mysql:
    image: library/mysql:5.5
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: ddb78359
      MYSQL_USER: fotawa
      MYSQL_PASSWORD: test
