fm\erpBundle\Entity\DireccionEnvio:
    type: entity
    manyToOne:
        cliente:
            targetEntity: clientes
            inversedBy: direcciones
            joinColumn:
                nullable: false
                name: cliente_id
                referencedColumnName: id 
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
        telefono:
            type: string
            length: '15'
        localidad:
            type: string
            length: 255
        provincia:
            type: string
            length: 255
        cp:
            type: string
            length: '15'
    lifecycleCallbacks: {  }
