fm\erpBundle\Entity\factura:
    type: entity
    manyToOne:
        sociedad:
            targetEntity: Sociedades
            inversedBy: facturas
            joinColumn:
                nullable: false
                name: sociedad_id
                referencedColumnName: id 
        cliente:
            targetEntity: clientes
            inversedBy: facturas
            joinColumn:
                nullable: false
                name: cliente_id
                referencedColumnName: id 
        serie:
            targetEntity: series
            joinColumn:
                nullable: false
                name: serie_id
                referencedColumnName: id 
        direccionEnvio:
            targetEntity: DireccionEnvio
            joinColumn:
                nullable: true
                name: direccion_id
                referencedColumnName: id 
    oneToMany:
        pedidos:
            targetEntity: PedidoItem
            mappedBy: factura
        misitems:
            targetEntity: item
            mappedBy: factura
            cascade: [persist]
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        codfactura:
            type: string
            length: 255
            nullable: true
        fechapagado:
            type: date
            nullable: true    
        fecha:
            type: date
        base:
            type: integer
            nullable: true
        iva:
            type: decimal
            precision: 5
            scale: 2
            options:
                default: 21.00
        observaciones:
            type: text
            nullable: true
        estado:
            type: integer
    lifecycleCallbacks: {  }
