fm\erpBundle\Entity\ordenesfabricacion:
    type: entity
    manyToOne:

        referencia:
            targetEntity: PedidoItem
            joinColumn:
                name: pedidoItemId
                referencedColumnName: id 
        mienvio:
            targetEntity: envios
            inversedBy: misordenes
            joinColumn:
                name: envio_id
                referencedColumnName: id  
        micajon:
            targetEntity: cajones
            joinColumn:
                name: cajon_id
                referencedColumnName: id 
    manyToMany:
        contenido:
            targetEntity: referencias
            joinTable:
                name: cajonreferencias
                joinColumns:
                    ordenfabricacion_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    referencia_id:
                        referencedColumnName: id        
    table: null
    repositoryClass: fm\erpBundle\Entity\ordenesfabricacionRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numeroserie:
            type: string
            length: 255
        producto:
            type: string
            length: 255
        origen:
            type: string
            length: 255
        estado:
            type: string
            length: 255
        fecha:
            type: datetime
    lifecycleCallbacks: {  }
