fm\erpBundle\Entity\Pedido:
    type: entity
    oneToMany:
        items:
            targetEntity: PedidoItem
            mappedBy: pedido
            cascade: [persist,remove]    
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fechaEntrega:
            type: date
            nullable: true
        fechaCreacion:
            type: datetime
            nullable: false
        fechaEnvio:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
