fm\erpBundle\Entity\Sociedades:
    type: entity
    oneToMany:
        facturas:
            targetEntity: factura
            mappedBy: sociedad
        direcciones:
            targetEntity: direcciones
            mappedBy: sociedad
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        razonSocial:
            type: string
            length: 255
            column: razon_social
        nif:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
        cp:
            type: string
            length: '10'
        localidad:
            type: string
            length: 255
        provincia:
            type: string
            length: 255    
        entidad:
            type: string
            length: 255
        iban:
            type: string
            length: 255
        codigoCuenta:
            type: string
            length: 255  
        observaciones:
            type: string
            length: 255 
    lifecycleCallbacks: {  }
