<?php

namespace fm\KitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * kitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kitsRepository extends EntityRepository
{
}
