<?php

namespace fm\erpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * proformasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proformasRepository extends EntityRepository
{
}
