<?php

namespace fm\erpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * seriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seriesRepository extends EntityRepository
{
	public function preset()
    {    
        $em = $this->getEntityManager();


		$q = $em->createQuery('update erpBundle:Series c set c.bydefault = ?1 where c.bydefault = ?2')
                    ->setParameter(1, 0)
                    ->setParameter(2, 1);

        $q->execute();
        

        return true;
    }

    public function findAll(){
        return $this->findBy(array(), array('bydefault' => 'DESC'));
    }
}
